name: Auto Merge IPTV

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Playlist and Replace HTTP with HTTPS
        run: |
          # ১. ফাইল ডাউনলোড
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          "https://iptvlive-beta.vercel.app" -o BDIX-Playlist.m3u

          # ২. ফাইল ডাউনলোড সফল হয়েছে কি না তা চেক করা
          if [ ! -s BDIX-Playlist.m3u ]; then
            echo "Error: Downloaded playlist is empty!"
            exit 1
          fi

          # ৩. http://iptvlive-beta কে https://iptvlive-beta তে পরিবর্তন
          sed -i 's|http://iptvlive-beta.vercel.app|https://iptvlive-beta.vercel.app|g' BDIX-Playlist.m3u

      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add BDIX-Playlist.m3u
          git commit -m "Auto update playlist with HTTPS" || exit 0
          git push
